
###
http://localhost:3000

###
GET http://localhost:3000/suny

###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users?search=&page=1&pageSize=5

###
GET http://localhost:3000/api/v1/users/count

###
GET http://localhost:3000/api/v1/users/31

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "emily.johnson@x.dummyjson.com"
}

###
POST http://localhost:3000/api/v1/

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "firstName": "Alice",
    "lastName": "Smith",
    "email": "alice.smith@example.com"
    
}

###
DELETE http://localhost:3000/api/v1/users/31

###
PATCH http://localhost:3000/api/v1/users/31
Content-Type: application/json

{
    "lastName": "Johnson"
}

###
GET http://localhost:3000/api/v1/products

###
GET http://localhost:3000/api/v1/cart/1

###
POST http://localhost:3000/api/v1/cart/1/
Content-Type: application/json

{
    "productId": 22,
    "quantity": 1
}